"""add dark_mode to user

Revision ID: c9a1e7b4d2f0
Revises: 2e25a15d11de
Create Date: 2026-05-29 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9a1e7b4d2f0"
down_revision = "2e25a15d11de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "dark_mode",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),  # ensure existing SQLite rows get a value
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("dark_mode")

    # ### end Alembic commands ###
